title: Food organics
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg_img: ''
    has_nav: true
    has_social: true
    logo_img: /images/dryfoods_dreamstime_m_9396865_440px.jpg
    tagline: Minimal and clean blog theme
    title: food plaza
  palette: green
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
